### ISSUE TITLE
ArgumentNullException when running with TestHost

### ISSUE THREAD

**Issue by twenzel** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#16]
When running the AspNet.Core application within the TestHost, an ArgumentNullException occurs:

```
System.ArgumentNullException : Value cannot be null.
Parameter name: repositoryAssembly
   at log4net.Core.LoggerManager.CreateRepository(Assembly repositoryAssembly, Type repositoryType)
   at Microsoft.Extensions.Logging.Log4NetProvider..ctor(String log4NetConfigFile, Func`3 exceptionFormatter)
   at YYY.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in YYY\Startup.cs:line 337
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at YYY.IntegrationTests.InvitationApiTests..ctor() in YYY.IntegrationTests\InvitationApiTests.cs:line 46
   at YYY.IntegrationTests.InvitationApiTests.InviteMethod..ctor()
```

Issue should be gone when Issue https://github.com/Microsoft/vstest/issues/649 will be fixed.

**Comment by huorswords** [comment]
Hello @twenzel ,

Thank you by your contribution.

I will integrate your changes to master and generate the proper nuget package as soon as possible.

I will close this issue when I finished to upload the nuget into nuget.org.

Regards

**Comment by twenzel** [comment]
Thank you.

**Comment by huorswords** [comment]
Hello @twenzel ,

I have included your changes into the develop & master branches, and deployed the nuget into  nuget.org.

Thank you very much by your collaboration. Regards
