### ISSUE TITLE
loggerFactory.AddLog4Net() not finding log4net.config when hosting the app in a Windows Service

### ISSUE THREAD

**Issue by leniel** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#48]
Hello,

I implemented the code described here:
[https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1)

The problem is that the app is crashing when starting the service...

When looking at Event Viewer, it shows that `log4net.config` is not being searched at the right location as configured per the URL linked above.

```
var pathToExe = Process.GetCurrentProcess().MainModule.FileName;
var pathToContentRoot = Path.GetDirectoryName(pathToExe);
```
`pathToContentRoot` is correctly pointing to the folder where the .exe file is placed and I can see that `log4net.config` is also present in this directory. However, the runtime is looking for the `log4net.config` file at `C:\WINDOWS\system32\log4net.config`.

Do you have any idea why this is happening?
Is there a way to hardcode the path to log4net.config?

This is the exception in Event Viewer:
```
Log Name:      Application
Source:        .NET Runtime
Date:          8/5/2018 3:52:47 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      LenielMaccaferri
Description:
Application: FileGetter.exe
CoreCLR Version: 4.6.26628.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not find file 'C:\WINDOWS\system32\log4net.config'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Microsoft.Extensions.Logging.Log4NetProvider.ParseLog4NetConfigFile(String filename)
   at Microsoft.Extensions.Logging.Log4NetProvider..ctor(String log4NetConfigFile, Boolean watch, IConfigurationSection configurationSection)
   at Microsoft.Extensions.Logging.Log4NetProvider..ctor(String log4NetConfigFile, Boolean watch)
   at Microsoft.Extensions.Logging.Log4NetExtensions.AddLog4Net(ILoggerFactory factory, String log4NetConfigFile, Boolean watch)
   at Microsoft.Extensions.Logging.Log4NetExtensions.AddLog4Net(ILoggerFactory factory, String log4NetConfigFile)
   at Microsoft.Extensions.Logging.Log4NetExtensions.AddLog4Net(ILoggerFactory factory)
   at Utilities.File.FileGetter.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Utilities.File.FileGetter\Startup.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Hosting.WindowsServices.WebHostService.OnStart(String[] args)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at Utilities.File.FileGetter.Program.Main(String[] args) in C:\Utilities.File.FileGetter\Program.cs:line 23
```

**Comment by leniel** [comment]
I was able to workaround the issue... in `Startup.cs => Configure` method:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
       {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));

            var pathToExe = Process.GetCurrentProcess().MainModule.FileName;
            var pathToContentRoot = Path.GetDirectoryName(pathToExe);

            // Setting the log file path and name dynamically...
            log4net.GlobalContext.Properties["LogFileName"] = pathToContentRoot + "\\ITVizion.Utilities.File.FileGetter.log"; //log file path

            //Log4Net logging
            loggerFactory.AddLog4Net(pathToContentRoot + "\\log4net.config", true);
            loggerFactory.AddDebug();
```

As you see, I had to provide the path (repeat the code) used in `Program.cs => Main` method. Not beautiful but it works.

**Comment by huorswords** [comment]
Hello @leniel,

Thank you by your question and for the workaround explanation.

Please take a look into this post, that explains what is the working directory on Windows Service and how to fix this as-designed issue.

https://haacked.com/archive/2004/06/29/current-directory-for-windows-service-is-not-what-you-expect.aspx/

Regards

**Comment by leniel** [comment]
@huorswords,

Adding `Directory.SetCurrentDirectory(System.AppDomain.CurrentDomain.BaseDirectory);` as the 1st line in Program.cs's `Main` method solves the issue once and for all.

Thanks for this awesome extension.

Regards,

Leniel
